config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => "plans#index"
  # Routes for the Coach resource:

  # CREATE
  get("/coaches/new", { :controller => "coaches", :action => "new_form" })
  post("/create_coach", { :controller => "coaches", :action => "create_row" })

  # READ
  get("/coaches", { :controller => "coaches", :action => "index" })
  get("/coaches/:id_to_display", { :controller => "coaches", :action => "show" })

  # UPDATE
  get("/coaches/:prefill_with_id/edit", { :controller => "coaches", :action => "edit_form" })
  post("/update_coach/:id_to_modify", { :controller => "coaches", :action => "update_row" })

  # DELETE
  get("/delete_coach/:id_to_remove", { :controller => "coaches", :action => "destroy_row" })
  get("/delete_coach_from_coach/:id_to_remove", { :controller => "coaches", :action => "destroy_row_from_coach" })

  #------------------------------

  # Routes for the Plan resource:

  # CREATE
  get("/plans/new", { :controller => "plans", :action => "new_form" })
  post("/create_plan", { :controller => "plans", :action => "create_row" })

  # READ
  get("/plans", { :controller => "plans", :action => "index" })
  get("/plans/:id_to_display", { :controller => "plans", :action => "show" })

  # UPDATE
  get("/plans/:prefill_with_id/edit", { :controller => "plans", :action => "edit_form" })
  post("/update_plan/:id_to_modify", { :controller => "plans", :action => "update_row" })

  # DELETE
  get("/delete_plan/:id_to_remove", { :controller => "plans", :action => "destroy_row" })

  #------------------------------

  devise_for :teachers
  # Routes for the Teacher resource:

  # READ
  get("/teachers", { :controller => "teachers", :action => "index" })
  get("/teachers/:id_to_display", { :controller => "teachers", :action => "show" })

  #------------------------------

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coach.rb
class Coach < ApplicationRecord
  # Direct associations

  belongs_to :coach,
             :class_name => "Teacher"

  # Indirect associations

  # Validations

end

app/models/plan.rb
class Plan < ApplicationRecord
  # Direct associations

  belongs_to :coach,
             :class_name => "Teacher",
             :counter_cache => true

  belongs_to :plan_owner,
             :class_name => "Teacher"

  # Indirect associations

  # Validations

end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Direct associations

  has_many   :coaches,
             :foreign_key => "coach_id",
             :dependent => :destroy

  has_one    :plan,
             :foreign_key => "plan_owner_id",
             :dependent => :destroy

  # Indirect associations

  # Validations

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_teacher!

  # protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, :keys => [:name])

    devise_parameter_sanitizer.permit(:account_update, :keys => [:name])
  end
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  def index
    @q = Coach.ransack(params[:q])
    @coaches = @q.result(:distinct => true).includes(:coach).page(params[:page]).per(10)

    render("coach_templates/index.html.erb")
  end

  def show
    @coach = Coach.find(params.fetch("id_to_display"))

    render("coach_templates/show.html.erb")
  end

  def new_form
    @coach = Coach.new

    render("coach_templates/new_form.html.erb")
  end

  def create_row
    @coach = Coach.new

    @coach.coach_id = params.fetch("coach_id")
    @coach.name = params.fetch("name")

    if @coach.valid?
      @coach.save

      redirect_back(:fallback_location => "/coaches", :notice => "Coach created successfully.")
    else
      render("coach_templates/new_form_with_errors.html.erb")
    end
  end

  def edit_form
    @coach = Coach.find(params.fetch("prefill_with_id"))

    render("coach_templates/edit_form.html.erb")
  end

  def update_row
    @coach = Coach.find(params.fetch("id_to_modify"))

    @coach.coach_id = params.fetch("coach_id")
    @coach.name = params.fetch("name")

    if @coach.valid?
      @coach.save

      redirect_to("/coaches/#{@coach.id}", :notice => "Coach updated successfully.")
    else
      render("coach_templates/edit_form_with_errors.html.erb")
    end
  end

  def destroy_row_from_coach
    @coach = Coach.find(params.fetch("id_to_remove"))

    @coach.destroy

    redirect_to("/teachers/#{@coach.coach_id}", notice: "Coach deleted successfully.")
  end

  def destroy_row
    @coach = Coach.find(params.fetch("id_to_remove"))

    @coach.destroy

    redirect_to("/coaches", :notice => "Coach deleted successfully.")
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @q = Plan.ransack(params[:q])
    @plans = @q.result(:distinct => true).includes(:plan_owner).page(params[:page]).per(10)

    render("plan_templates/index.html.erb")
  end

  def show
    @plan = Plan.find(params.fetch("id_to_display"))

    render("plan_templates/show.html.erb")
  end

  def new_form
    @plan = Plan.new

    render("plan_templates/new_form.html.erb")
  end

  def create_row
    @plan = Plan.new

    @plan.plan_description = params.fetch("plan_description")
    @plan.plan_owner_id = params.fetch("plan_owner_id")
    @plan.coach_id = params.fetch("coach_id")

    if @plan.valid?
      @plan.save

      redirect_back(:fallback_location => "/plans", :notice => "Plan created successfully.")
    else
      render("plan_templates/new_form_with_errors.html.erb")
    end
  end

  def edit_form
    @plan = Plan.find(params.fetch("prefill_with_id"))

    render("plan_templates/edit_form.html.erb")
  end

  def update_row
    @plan = Plan.find(params.fetch("id_to_modify"))

    @plan.plan_description = params.fetch("plan_description")
    @plan.plan_owner_id = params.fetch("plan_owner_id")
    @plan.coach_id = params.fetch("coach_id")

    if @plan.valid?
      @plan.save

      redirect_to("/plans/#{@plan.id}", :notice => "Plan updated successfully.")
    else
      render("plan_templates/edit_form_with_errors.html.erb")
    end
  end

  def destroy_row
    @plan = Plan.find(params.fetch("id_to_remove"))

    @plan.destroy

    redirect_to("/plans", :notice => "Plan deleted successfully.")
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teachers = Teacher.page(params[:page]).per(10)

    render("teacher_templates/index.html.erb")
  end

  def show
    @teacher = Teacher.find(params.fetch("id_to_display"))

    render("teacher_templates/show.html.erb")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper  

  def collapse_search_form
    if params[:q].blank?
      "collapse"
    else
      ""
    end
  end

end

app/views/coach_templates/_coaches_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "coaches_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :coach_name_cont, "Teacher name contains" %>
    <%= f.text_field :coach_name_cont, :class => "form-control", :placeholder => "Teacher name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/coaches" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#coaches_filters">
  Show filters
</a>

app/views/coach_templates/edit_form.html.erb
<h1>
  Edit coach #<%= @coach.id %>
</h1>

<hr>

<form action="/update_coach/<%= @coach.id %>" method="post">

  <div class="form-group">
    <label for="coach_id">
      Coach
    </label>

    <%= select_tag(:coach_id, options_from_collection_for_select(Teacher.all, :id, :name, @coach.coach_id), :class => "form-control") %>
  </div>

  <div class="form-group">
    <label for="name">
      Name
    </label>

    <input type="text" id="name" name="name" class="form-control" value="<%= @coach.name %>">
  </div>

  <button class="btn btn-block btn-outline-secondary">
    Update coach
  </button>
</form>

<hr>

<a href="/coaches">
  Go back
</a>

app/views/coach_templates/edit_form_with_errors.html.erb
<% if @coach.errors.any? %>
  <% @coach.errors.full_messages.each do |message| %>
    <div class="alert">
      <%= message %>
    </div>
  <% end %>
<% end %>

<h1>
  Edit coach #<%= @coach.id %>
</h1>

<hr>

<form action="/update_coach/<%= @coach.id %>" method="post">

  <div class="form-group">
    <label for="coach_id">
      Coach
    </label>

    <%= select_tag(:coach_id, options_from_collection_for_select(Teacher.all, :id, :name, @coach.coach_id), :class => "form-control") %>
  </div>

  <div class="form-group">
    <label for="name">
      Name
    </label>

    <input type="text" id="name" name="name" class="form-control" value="<%= @coach.name %>">
  </div>

  <button class="btn btn-block btn-outline-secondary">
    Update coach
  </button>
</form>

<hr>

<a href="/coaches">
  Go back
</a>

app/views/coach_templates/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1>
      All coaches
    </h1>

    <a href="/coaches/new" class="btn btn-block btn-outline-secondary">
      Add a new coach
    </a>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "coach_templates/coaches_search_form" %>
  </div>
</div>



<hr>

<div class="row mb-3">
  <div class="col-md-12">
    <table class="table">
      <tr>
        <th>
          ID
        </th>

        <th>
          Coach
        </th>

        <th>
          Name
        </th>

        <th>
          Created at
        </th>

        <th>
          Updated at
        </th>

        <th>
        </th>
      </tr>

      <% @coaches.each do |coach| %>
      <tr>
        <td>
          <%= coach.id %>
        </td>

        <td>
          <% if coach.coach.present? %>
            <a href="/teachers/<%= coach.coach.id %>">
              <%= coach.coach.name %>
            </a>
          <% end %>
        </td>

        <td>
          <%= coach.name %>
        </td>

        <td>
          <%= time_ago_in_words(coach.created_at) %> ago
        </td>

        <td>
          <%= time_ago_in_words(coach.updated_at) %> ago
        </td>

        <td>
          <a href="/coaches/<%= coach.id %>">
            Show details
          </a>
        </td>
      </tr>
      <% end %>
    </table>

    <div class="row mb-3">
      <div class="col-md-12">
        <%= paginate @coaches, theme: "twitter-bootstrap-4" %>
      </div>
    </div>

  </div>
</div>

app/views/coach_templates/new_form.html.erb
<h1>
  Add a new coach
</h1>


<hr>

<form action="/create_coach" method="post">

  <div class="form-group">
    <label for="coach_id">
      Coach
    </label>

    <%= select_tag(:coach_id, options_from_collection_for_select(Teacher.all, :id, :name, @coach.coach_id), :class => "form-control") %>
  </div>

  <div class="form-group">
    <label for="name">
      Name
    </label>

    <input type="text" id="name" name="name" class="form-control">
  </div>

  <button class="btn btn-block btn-outline-secondary">
    Create coach
  </button>
</form>

<hr>

<a href="/coaches">
  Go back
</a>

app/views/coach_templates/new_form_with_errors.html.erb
<% if @coach.present? %>
  <% if @coach.errors.any? %>
    <% @coach.errors.full_messages.each do |message| %>
      <div class="alert alert-danger">
        <%= message %>
      </div>
    <% end %>
  <% end %>
<% end %>

<h1>
  Add a new coach
</h1>


<hr>

<form action="/create_coach" method="post">

  <div class="form-group">
    <label for="coach_id">
      Coach
    </label>

    <%= select_tag(:coach_id, options_from_collection_for_select(Teacher.all, :id, :name, @coach.coach_id), :class => "form-control") %>
  </div>

  <div class="form-group">
    <label for="name">
      Name
    </label>

    <input type="text" id="name" name="name" class="form-control" value="<%= @coach.name %>">
  </div>

  <button class="btn btn-block btn-outline-secondary">
    Create coach
  </button>
</form>

<hr>

<a href="/coaches">
  Go back
</a>

app/views/coach_templates/show.html.erb
<div class="row mb-3">
  <div class="col-md-8 offset-md-2">
    <h1>
      Coach #<%= @coach.id %> details
    </h1>

    <div class="row mb-3">
      <div class="col">
        <a href="/coaches" class="btn btn-block btn-outline-secondary">
          Go back
        </a>
      </div>

      <div class="col">
        <a href="/coaches/<%= @coach.id %>/edit" class="btn btn-block btn-outline-secondary">
          Edit coach
        </a>
      </div>

      <div class="col">
        <a href="/delete_coach/<%= @coach.id %>" class="btn btn-block btn-outline-secondary">
          Delete coach
        </a>
      </div>
    </div>

    <dl>
      <dt>
        Coach
      </dt>
      <dd>
        <% if @coach.coach.present? %>
          <a href="/teachers/<%= @coach.coach_id %>">
            <%= @coach.coach.name %>
          </a>
        <% end %>
      </dd>

      <dt>
        Name
      </dt>
      <dd>
        <%= @coach.name %>
      </dd>

      <dt>
        Created at
      </dt>
      <dd>
        <%= time_ago_in_words(@coach.created_at) %> ago
      </dd>

      <dt>
        Updated at
      </dt>
      <dd>
        <%= time_ago_in_words(@coach.updated_at) %> ago
      </dd>
    </dl>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    Teacherplan
  </title>

  <%= render "shared/bootstrapcdn_assets" %>

  <%= csrf_meta_tags %>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/css/tempusdominus-bootstrap-4.min.css" />
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js"></script>
  <script src="//maps.google.com/maps/api/js?v=3.24&key=AIzaSyCOTPWiuvyyo6sKoIBzKA4-1ol-vTOIOlM"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>


  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta charset="utf-8">
  <style>
    body { padding-bottom: 70px }
  </style>
</head>

<body>
  <%= render "shared/navbar" %>

  <div class="container">
    <%= render "shared/flashes" %>

    <%= yield %>
  </div>

</body>
</html>

app/views/plan_templates/_plans_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "plans_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :plan_description_cont, "Plan description contains" %>
    <%= f.text_field :plan_description_cont, :class => "form-control", :placeholder => "Plan description contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :plan_owner_name_cont, "Teacher name contains" %>
    <%= f.text_field :plan_owner_name_cont, :class => "form-control", :placeholder => "Teacher name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :coach_name_cont, "Teacher name contains" %>
    <%= f.text_field :coach_name_cont, :class => "form-control", :placeholder => "Teacher name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/plans" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#plans_filters">
  Show filters
</a>

app/views/plan_templates/edit_form.html.erb
<h1>
  Edit plan #<%= @plan.id %>
</h1>

<hr>

<form action="/update_plan/<%= @plan.id %>" method="post">

  <div class="form-group">
    <label for="plan_description">
      Plan description
    </label>

    <input type="text" id="plan_description" name="plan_description" class="form-control" value="<%= @plan.plan_description %>">
  </div>

  <div class="form-group">
    <label for="plan_owner_id">
      Plan owner
    </label>

    <%= select_tag(:plan_owner_id, options_from_collection_for_select(Teacher.all, :id, :name, @plan.plan_owner_id), :class => "form-control") %>
  </div>

  <div class="form-group">
    <label for="coach_id">
      Coach
    </label>

    <input type="text" id="coach_id" name="coach_id" class="form-control" value="<%= @plan.coach_id %>">
  </div>

  <button class="btn btn-block btn-outline-secondary">
    Update plan
  </button>
</form>

<hr>

<a href="/plans">
  Go back
</a>

app/views/plan_templates/edit_form_with_errors.html.erb
<% if @plan.errors.any? %>
  <% @plan.errors.full_messages.each do |message| %>
    <div class="alert">
      <%= message %>
    </div>
  <% end %>
<% end %>

<h1>
  Edit plan #<%= @plan.id %>
</h1>

<hr>

<form action="/update_plan/<%= @plan.id %>" method="post">

  <div class="form-group">
    <label for="plan_description">
      Plan description
    </label>

    <input type="text" id="plan_description" name="plan_description" class="form-control" value="<%= @plan.plan_description %>">
  </div>

  <div class="form-group">
    <label for="plan_owner_id">
      Plan owner
    </label>

    <%= select_tag(:plan_owner_id, options_from_collection_for_select(Teacher.all, :id, :name, @plan.plan_owner_id), :class => "form-control") %>
  </div>

  <div class="form-group">
    <label for="coach_id">
      Coach
    </label>

    <input type="text" id="coach_id" name="coach_id" class="form-control" value="<%= @plan.coach_id %>">
  </div>

  <button class="btn btn-block btn-outline-secondary">
    Update plan
  </button>
</form>

<hr>

<a href="/plans">
  Go back
</a>

app/views/plan_templates/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1>
      All plans
    </h1>

    <a href="/plans/new" class="btn btn-block btn-outline-secondary">
      Add a new plan
    </a>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "plan_templates/plans_search_form" %>
  </div>
</div>



<hr>

<div class="row mb-3">
  <div class="col-md-12">
    <table class="table">
      <tr>
        <th>
          ID
        </th>

        <th>
          Plan description
        </th>

        <th>
          Coach
        </th>

        <th>
          Plan owner
        </th>

        <th>
          Created at
        </th>

        <th>
          Updated at
        </th>

        <th>
        </th>
      </tr>

      <% @plans.each do |plan| %>
      <tr>
        <td>
          <%= plan.id %>
        </td>

        <td>
          <%= plan.plan_description %>
        </td>

        <td>
          <% if plan.coach.present? %>
            <a href="/teachers/<%= plan.coach.id %>">
              <%= plan.coach.name %>
            </a>
          <% end %>
        </td>

        <td>
          <% if plan.plan_owner.present? %>
            <a href="/teachers/<%= plan.plan_owner.id %>">
              <%= plan.plan_owner.name %>
            </a>
          <% end %>
        </td>

        <td>
          <%= time_ago_in_words(plan.created_at) %> ago
        </td>

        <td>
          <%= time_ago_in_words(plan.updated_at) %> ago
        </td>

        <td>
          <a href="/plans/<%= plan.id %>">
            Show details
          </a>
        </td>
      </tr>
      <% end %>
    </table>

    <div class="row mb-3">
      <div class="col-md-12">
        <%= paginate @plans, theme: "twitter-bootstrap-4" %>
      </div>
    </div>

  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
  <div class="container">
    <a class="navbar-brand" href="/">
      Teacherplan
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsible-nav-links" aria-controls="collapsible-nav-links" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="collapsible-nav-links">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Resources
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a href="/coaches" class="dropdown-item">
              Coaches
            </a>
            <a href="/plans" class="dropdown-item">
              Plans
            </a>
            <a href="/teachers" class="dropdown-item">
              Teachers
            </a>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if current_teacher.blank? %>
          <li class="nav-item">
            <a href="/teachers/sign_in" class="nav-link">
              Sign in
            </a>
          </li>

          <li class="nav-item">
            <a href="/teachers/sign_up" class="nav-link">
              Sign up
            </a>
          </li>
        <% else %>
          <li class="nav-item">
            <a href="/teachers/edit" class="nav-link">
              Edit profile
            </a>
          </li>

          <li class="nav-item">
            <a href="/teachers/sign_out" data-method="delete" class="nav-link">
              Sign out
            </a>
          </li>
        <% end %>
      </ul>
</nav>

app/views/teachers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>